"""empty message

Revision ID: 5a9e1401084b
Revises: e829342564a2
Create Date: 2023-01-16 10:07:40.778781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9e1401084b'
down_revision = 'e829342564a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clothes_Goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('material', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Clothes_Goods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_material'), ['material'], unique=False)
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_size'), ['size'], unique=False)

    op.create_table('Food_Goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('fruit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Food_Goods_description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('ix_Food_Goods_name'), ['name'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Users_admin'), ['admin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_admin'))
        batch_op.drop_column('admin')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Food_Goods_name'))
        batch_op.drop_index(batch_op.f('ix_Food_Goods_description'))

    op.drop_table('Food_Goods')
    with op.batch_alter_table('Clothes_Goods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_size'))
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_name'))
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_material'))
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_description'))

    op.drop_table('Clothes_Goods')
    # ### end Alembic commands ###
