"""empty message

Revision ID: 5e75ab6a1d7e
Revises: ba0498351ca2
Create Date: 2023-01-17 17:17:20.334735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e75ab6a1d7e'
down_revision = 'ba0498351ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clothes_Goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descreption', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('matherial', sa.String(length=75), nullable=True))
        batch_op.drop_index('ix_Clothes_Goods_description')
        batch_op.drop_index('ix_Clothes_Goods_material')
        batch_op.drop_index('ix_Clothes_Goods_name')
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_descreption'), ['descreption'], unique=False)
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_matherial'), ['matherial'], unique=False)
        batch_op.create_index(batch_op.f('ix_Clothes_Goods_price'), ['price'], unique=False)
        batch_op.drop_column('material')
        batch_op.drop_column('description')

    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.drop_index('ix_Food_Goods_descreption')
        batch_op.create_index(batch_op.f('ix_Food_Goods_descreption'), ['descreption'], unique=False)
        batch_op.drop_index('ix_Food_Goods_name')
        batch_op.create_index(batch_op.f('ix_Food_Goods_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Food_Goods_name'))
        batch_op.create_index('ix_Food_Goods_name', ['name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_Food_Goods_descreption'))
        batch_op.create_index('ix_Food_Goods_descreption', ['descreption'], unique=False)

    with op.batch_alter_table('Clothes_Goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('material', sa.VARCHAR(length=75), nullable=True))
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_price'))
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_matherial'))
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_descreption'))
        batch_op.drop_index(batch_op.f('ix_Clothes_Goods_name'))
        batch_op.create_index('ix_Clothes_Goods_name', ['name'], unique=False)
        batch_op.create_index('ix_Clothes_Goods_material', ['material'], unique=False)
        batch_op.create_index('ix_Clothes_Goods_description', ['description'], unique=False)
        batch_op.drop_column('matherial')
        batch_op.drop_column('price')
        batch_op.drop_column('descreption')

    # ### end Alembic commands ###
