"""empty message

Revision ID: 8d27bb61f581
Revises: e3045effb50a
Create Date: 2023-05-19 21:18:51.515115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d27bb61f581'
down_revision = 'e3045effb50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.drop_index('ix_Food_Goods_descreption')
        batch_op.drop_index('ix_Food_Goods_name')
        batch_op.drop_index('ix_Food_Goods_price')

    op.drop_table('Food_Goods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food_Goods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('descreption', sa.VARCHAR(length=80), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('developer', sa.VARCHAR(), nullable=True),
    sa.Column('publisher', sa.VARCHAR(), nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.create_index('ix_Food_Goods_price', ['price'], unique=False)
        batch_op.create_index('ix_Food_Goods_name', ['name'], unique=False)
        batch_op.create_index('ix_Food_Goods_descreption', ['descreption'], unique=False)

    # ### end Alembic commands ###
