"""empty message

Revision ID: ba0498351ca2
Revises: aa287dbc402f
Create Date: 2023-01-17 17:10:08.816447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0498351ca2'
down_revision = 'aa287dbc402f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descreption', sa.String(length=80), nullable=True))
        batch_op.drop_index('ix_Food_Goods_description')
        batch_op.create_index(batch_op.f('ix_Food_Goods_descreption'), ['descreption'], unique=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_index(batch_op.f('ix_Food_Goods_descreption'))
        batch_op.create_index('ix_Food_Goods_description', ['description'], unique=False)
        batch_op.drop_column('descreption')

    # ### end Alembic commands ###
