"""empty message

Revision ID: fcbc3fbef7c7
Revises: f5ef404b90b5
Create Date: 2023-05-27 16:28:40.329853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbc3fbef7c7'
down_revision = 'f5ef404b90b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###
